apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: flask-ingress-virtual-host
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: v1.flask-app.com
    http:
      paths:
      - backend:
          serviceName: flask-dep
          servicePort: 4080
  - host: v2.flask-app.com
    http:
      paths:
      - backend:
          serviceName: flask-dep-v2
          servicePort: 4080
~                                
